services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    ports:
      - "${NGINX_PORT:-8000}:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  php:
    build: ./php
    container_name: php_fpm
    user: "${PUID:-1000}:${PGID:-1000}"
    volumes:
      - ./src:/var/www/html
    environment:
      # Variáveis para a conexão MySQL
      DB_HOST_MYSQL: 'mysql'
      DB_DATABASE_MYSQL: '${MYSQL_DATABASE}'
      DB_USER_MYSQL: '${MYSQL_USER}'
      DB_PASSWORD_MYSQL: '${MYSQL_PASSWORD}'

      # Variáveis para a conexão PostgreSQL
      DB_HOST_POSTGRES: 'postgres'
      DB_DATABASE_POSTGRES: '${POSTGRES_DATABASE}'
      DB_USER_POSTGRES: '${POSTGRES_USER}'
      DB_PASSWORD_POSTGRES: '${POSTGRES_PASSWORD}'

      # Variáveis para a conexão Redis
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    depends_on:
      - redis
      - mysql
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-root}'
      MYSQL_DATABASE: '${MYSQL_DATABASE:-db_mysql}'
      MYSQL_USER: '${MYSQL_USER:-user}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-password}'
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 256M

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: '${POSTGRES_DATABASE:-db_postgres}'
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
    ports:
      - "${POSGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 256M

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          memory: 128M

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander_ui
    restart: always
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

volumes:
  db-data:
  postgres-data:
  redis-data:
