# Definição dos serviços (contêineres)
services:

  # Serviço 1: Nginx (Servidor Web)
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    ports:
      # Expõe a porta 80 do contêiner na porta 8000 da sua máquina
      - "8000:80"
    volumes:
      # Monta a pasta de código fonte
      - ./src:/var/www/html
      # Monta o arquivo de configuração do Nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  # Serviço 2: PHP-FPM (Processador PHP)
  php:
    # 'build' instrui o Docker a construir a imagem a partir do Dockerfile na pasta 'php'
    build: ./php
    container_name: php_fpm_processor
    volumes:
      # Monta a pasta de código fonte para que o PHP possa acessá-la
      # Deve ser o mesmo caminho montado pelo Nginx
      - ./src:/var/www/html
  
  # Serviço 3: Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'meu_banco'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user_password'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  # Serviço 4: phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ui
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

# Definição dos volumes nomeados
volumes:
  db-data:
